"use client";
import {useEffect,useMemo,useState} from "react"; import Link from "next/link"; import axios from "axios"; import toast from "react-hot-toast"; import {useAuthStore} from "@/store/authStore"; import {ROLES} from "@/constants/roles"; import Button from "@/components/ui/Button"; import {formatNaira} from "@/utils/formatNaira"; import {formatDateTime} from "@/utils/formatDate"; import styles from "./page.module.css";
export default function ProcurementBatchesPage(){const user=useAuthStore(s=>s.user);const[batches,setBatches]=useState([]);const[approved,setApproved]=useState([]);const[selected,setSelected]=useState([]);const[loading,setLoading]=useState(true);const[creating,setCreating]=useState(false);const isVc=user?.role===ROLES.VC;
 async function load(){setLoading(true);try{const req=[axios.get("/api/procurement-batches")];if(isVc)req.push(axios.get("/api/requisitions",{params:{status:"approved"}}));const[b,a]=await Promise.all(req);setBatches(b.data.batches||[]);if(a)setApproved((a.data.requisitions||[]).filter(r=>r.procurementStatus==="ready"&&!r.procurementBatch));}catch(e){toast.error(e.response?.data?.message||"Failed to load Procurement Batches.");}finally{setLoading(false);}}
 useEffect(()=>{if(user)load();},[user?.role]); const total=useMemo(()=>approved.filter(r=>selected.includes(r._id)).reduce((s,r)=>s+Number(r.estimatedCost||0),0),[approved,selected]); const toggle=id=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 async function createBatch(){if(!selected.length)return toast.error("Select at least one approved requisition.");setCreating(true);try{const{data}=await axios.post("/api/procurement-batches",{requisitionIds:selected});toast.success(`Batch ${data.batch.batchNumber} created.`);setSelected([]);await load();}catch(e){toast.error(e.response?.data?.message||"Failed to create batch.");}finally{setCreating(false);}}
 return <div className={styles.wrapper}><div className={styles.header}><div><h1 className={styles.heading}>Procurement Batches</h1><p className={styles.subheading}>{isVc?"Group fully approved requisitions and authorize their submission to Procurement.":"View VC-authorized procurement submissions."}</p></div>{isVc&&<Button onClick={createBatch} loading={creating} disabled={!selected.length}><i className="bi bi-collection"/> Create Batch ({selected.length})</Button>}</div>
 {isVc&&<section className={styles.section}><div className={styles.sectionHeader}><div><h2>Approved and Ready for Procurement</h2><p>{selected.length} selected · {formatNaira(total)}</p></div><button className={styles.selectAll} onClick={()=>setSelected(selected.length===approved.length&&approved.length?[]:approved.map(r=>r._id))}>{selected.length===approved.length&&approved.length?"Clear all":"Select all"}</button></div>{loading?<p>Loading…</p>:!approved.length?<p className={styles.muted}>There are no unbatched approved requisitions ready for Procurement.</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th></th><th>Requisition</th><th>Department</th><th>Purpose</th><th>Value</th></tr></thead><tbody>{approved.map(r=><tr key={r._id}><td><input type="checkbox" checked={selected.includes(r._id)} onChange={()=>toggle(r._id)}/></td><td>{r.requisitionNumber}</td><td>{r.department}</td><td>{r.purpose||"-"}</td><td>{formatNaira(r.estimatedCost)}</td></tr>)}</tbody></table></div>}</section>}
 <section className={styles.section}><h2>{isVc?"My Batches":"Submitted to Procurement"}</h2>{loading?<p>Loading…</p>:!batches.length?<p className={styles.muted}>No Procurement Batches found.</p>:<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Batch</th><th>Requisitions</th><th>Total</th><th>Status</th><th>Date</th><th></th></tr></thead><tbody>{batches.map(b=><tr key={b._id}><td>{b.batchNumber}</td><td>{b.requisitions.length}</td><td>{formatNaira(b.totalEstimatedCost)}</td><td><span className={`${styles.badge} ${b.status==="submitted"?styles.submitted:""}`}>{b.status}</span></td><td>{formatDateTime(b.createdAt)}</td><td><Link href={`/procurement-batches/${b._id}`} className={styles.link}>View</Link></td></tr>)}</tbody></table></div>}</section></div>;}
