"use client";
import {useEffect,useState} from "react"; import {useParams,useRouter} from "next/navigation"; import axios from "axios"; import toast from "react-hot-toast"; import Button from "@/components/ui/Button"; import {useAuthStore} from "@/store/authStore"; import {ROLES} from "@/constants/roles"; import {formatNaira} from "@/utils/formatNaira"; import {formatDateTime} from "@/utils/formatDate"; import styles from "./page.module.css";
export default function ProcurementBatchDetailPage(){const{id}=useParams();const router=useRouter();const user=useAuthStore(s=>s.user);const[batch,setBatch]=useState(null);const[password,setPassword]=useState("");const[loading,setLoading]=useState(true);const[signing,setSigning]=useState(false);
 async function load(){try{const{data}=await axios.get(`/api/procurement-batches/${id}`);setBatch(data.batch);}catch(e){toast.error(e.response?.data?.message||"Failed to load batch.");}finally{setLoading(false);}} useEffect(()=>{if(id)load();},[id]);
 async function signAndSubmit(){if(!password)return toast.error("Enter your current password to authorize the signing action.");if(!window.confirm(`Sign and submit ${batch.batchNumber} to Procurement? This action cannot be undone.`))return;setSigning(true);try{const r=await axios.post(`/api/procurement-batches/${id}/sign`,{password},{responseType:"blob"});const url=URL.createObjectURL(new Blob([r.data],{type:"application/pdf"}));window.open(url,"_blank","noopener,noreferrer");setPassword("");toast.success("Batch signed and submitted to Procurement.");await load();}catch(e){let m="Signing failed.";if(e.response?.data instanceof Blob){try{const t=await e.response.data.text();m=JSON.parse(t).message||m;}catch{}}else m=e.response?.data?.message||m;toast.error(m);}finally{setSigning(false);}}
 function openPdf(){window.open(`/api/procurement-batches/${id}/pdf`,"_blank","noopener,noreferrer");}
 if(loading)return <p>Loading…</p>;if(!batch)return <p>Procurement Batch not found.</p>;const canSign=user?.role===ROLES.VC&&batch.status==="draft";
 return <div className={styles.wrapper}><div className={styles.header}><div><h1 className={styles.heading}>{batch.batchNumber}</h1><p className={styles.subheading}>Procurement Submission Batch</p></div><Button variant="secondary" onClick={()=>router.push("/procurement-batches")}><i className="bi bi-arrow-left"/> Back</Button></div>
 <section className={styles.summary}><div><span>Status</span><strong>{batch.status}</strong></div><div><span>Requisitions</span><strong>{batch.requisitions.length}</strong></div><div><span>Total value</span><strong>{formatNaira(batch.totalEstimatedCost)}</strong></div><div><span>Created</span><strong>{formatDateTime(batch.createdAt)}</strong></div>{batch.signedAt&&<div><span>Signed</span><strong>{formatDateTime(batch.signedAt)}</strong></div>}</section>
 <section className={styles.section}><h2>Requisitions in this Batch</h2>{batch.requisitions.map(r=><article className={styles.requisition} key={String(r.requisition)}><div className={styles.reqHeader}><div><h3>{r.requisitionNumber}</h3><p>{r.department} · {r.requesterName}</p></div><strong>{formatNaira(r.estimatedCost)}</strong></div><p><b>Purpose:</b> {r.purpose||"-"}</p><div className={styles.items}>{(r.items||[]).map((item,i)=><div key={`${r.requisition}-${i}`}><span>{item.name} × {item.quantity}</span><span>{formatNaira(item.totalCost)}</span></div>)}</div></article>)}</section>
 {canSign&&<section className={styles.signSection}><h2>VC Authorization</h2><p>The server will re-check every requisition, verify its integrity snapshot, require your current password, attach your encrypted signature, hash the final PDF, and permanently submit the batch to Procurement.</p><label className={styles.label}>Current VC password<input className={styles.input} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><Button onClick={signAndSubmit} loading={signing}><i className="bi bi-pen"/> Sign &amp; Submit to Procurement</Button></section>}
 {batch.status==="submitted"&&<section className={styles.signed}><div><i className="bi bi-shield-check"/><div><h2>Signed and submitted</h2><p>Authorized by {batch.signedBy?.fullName||"Vice-Chancellor"} on {formatDateTime(batch.signedAt)}.</p><small>Document hash: {batch.documentHash}</small></div></div><Button onClick={openPdf}><i className="bi bi-file-earmark-pdf"/> View Signed PDF</Button></section>}</div>; }
